### PR TITLE
[v3] Compilation error with JDK11

### PR DESCRIPTION
**Pull request by getzze**
I could not compile on Arch (using jdk-openjdk11.0.1), wiith this patch it compiles, but I am not sure that the problem it really solved. I thought it could be related to this bug:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=5066027

See https://aur.archlinux.org/packages/tiny-media-manager-git/

### CODE REVIEW

**Comment by mlaggner** [comment]
looks good on manjaro/java8

thanks for your fix
