### ISSUE TITLE
TMM 2.7.1 java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by and1g** [tinyMediaManager/tinyMediaManager#7]
After updating to 2.7.0/2.7.1, Tiny Media Manager fails to start. Extracting to a clean directory leads to the same behaviour. Running tinyMediaManager.sh just displays the splash screen which disappears and then nothing happens. Running the jar directly from the console gives slightly more information. (see below)

**Steps to reproduce:**
- Download fresh copy of tmm_2.7.1_875ecb9_linux.tar.gz
- Extract to $HOME/tmm
- % cd $HOME/tmm
- % java -jar tmm.jar 

**Expected behaviour:**
TMM starts up.

**Actual behaviour:**
TMM crashes and leaves this error message:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
            at org.tinymediamanager.TinyMediaManager.<clinit>(TinyMediaManager.java:77)
    Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
            at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            ... 1 more

**System information:**
Gentoo Linux amd64
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Tiny Media Manager 2.7.1_875ecb9_linux

**Comment by mlaggner** [comment]
please try to delete the tmm.jar and run the shellscript again; this will trigger the updater to check all files again

**Comment by and1g** [comment]
No change. tmm.jar gets downloaded again and running it still results in the crash explained in the first post.
Could this possibly be related to some faulty system library?

**Comment by myron0815** [comment]
"java -jar tmm.jar" does not work, since the jar does not know its libraries (anylonger)
we need to specify the classpath; something like
"java -cp lib/* -jar tmm.jar

**Comment by and1g** [comment]
Thanks. But now I get

    % LANG= java -cp lib/* -jar tmm.jar 
    Error: Could not find or load main class lib.asm.jar

And why is running `tinyMediaManager.sh` not working either, failing with no error message?

**Comment by mlaggner** [comment]
okay, `java -cp lib/* -jar tmm.jar` gives the same problem here.
please try to run the shellscript and have a look at the file `launcher.log` afterwards. You will find the whole command to start tmm (this is generated per system) in there at the bottom.
If you copy that and execute it in a terminal you will get more information.

**Comment by and1g** [comment]
Oh well that's quite a long command line...
The output:

    CompilerOracle: exclude ca/odell/glazedlists/impl/filter/TextMatchers.matches
    CompilerOracle: exclude ca/odell/glazedlists/impl/filter/BoyerMooreCaseInsensitiveTextSearchStrategy.indexOf
    2016-01-02 13:53:29,357 INFO  [main] org.tinymediamanager.TinyMediaManager:138 - =====================================================
    2016-01-02 13:53:29,359 INFO  [main] org.tinymediamanager.TinyMediaManager:139 - === tinyMediaManager (c) 2012-2015 Manuel Laggner ===
    2016-01-02 13:53:29,359 INFO  [main] org.tinymediamanager.TinyMediaManager:140 - =====================================================
    2016-01-02 13:53:29,360 INFO  [main] org.tinymediamanager.TinyMediaManager:141 - tmm.version      : 2.7.1
    2016-01-02 13:53:29,512 DEBUG [main] org.tinymediamanager.core.Settings:235 - Loading settings from data
    2016-01-02 13:53:29,799 INFO  [main] org.tinymediamanager.TinyMediaManager:147 - os.name          : Linux
    2016-01-02 13:53:29,799 INFO  [main] org.tinymediamanager.TinyMediaManager:148 - os.version       : 4.3.2-gentoo
    2016-01-02 13:53:29,799 INFO  [main] org.tinymediamanager.TinyMediaManager:149 - os.arch          : amd64
    2016-01-02 13:53:29,806 INFO  [main] org.tinymediamanager.TinyMediaManager:151 - java.version     : 1.8.0_66
    2016-01-02 13:53:29,806 INFO  [main] org.tinymediamanager.TinyMediaManager:505 - default encoding : UTF-8 | UTF8 | UTF-8
    2016-01-02 13:53:29,806 INFO  [main] org.tinymediamanager.TinyMediaManager:505 - set encoding to  : UTF-8 | UTF8 | UTF-8
    2016-01-02 13:53:29,806 INFO  [main] org.tinymediamanager.TinyMediaManager:176 - System language  : de_DE
    2016-01-02 13:53:29,806 INFO  [main] org.tinymediamanager.TinyMediaManager:177 - GUI language     : de_DE
    2016-01-02 13:53:29,808 INFO  [main] org.tinymediamanager.TinyMediaManager:178 - Scraper language : Deutsch
    2016-01-02 13:53:29,808 INFO  [main] org.tinymediamanager.TinyMediaManager:179 - TV Scraper lang  : Deutsch
    2016-01-02 13:53:29,909 INFO  [main] org.tinymediamanager.TinyMediaManager:227 - =====================================================
    2016-01-02 13:53:29,917 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (0%) starting tinyMediaManager
    2016-01-02 13:53:29,918 INFO  [main] org.tinymediamanager.TinyMediaManager:232 - starting tinyMediaManager
    2016-01-02 13:53:29,919 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (20%) loading MediaInfo libs
    2016-01-02 13:53:29,943 DEBUG [main] o.t.thirdparty.MediaInfoUtils:87 - Loading native mediainfo lib from: native/linux-x64
    [1]    21112 segmentation fault (core dumped)  java -classpath  -Dcom.threerings.getdown=true -Xms64m -Xmx512m -Xss512k

Missing dependency or incompatiblity with mediainfo?

**Comment by mlaggner** [comment]
okay, just what I thought..
there is a problem between the shipped mediainfo and the system one at the moment.
I am just setting up a virtual machine to get a clue what is causing the problem.

Just as a workaroung: install libmediainfo and libzen from your repository and copy the libs into the tmm subdir native/linux-x64

**Comment by mlaggner** [comment]
btw: could you add `-Djna.debug_load=true` just before `org.tinymediamanager.TinyMediaManager` in the start command and send us the lines after `org.tinymediamanager.TinyMediaManager:397 - Startup (20%) loading MediaInfo libs`

**Comment by and1g** [comment]
Thank you, now it is working.
It seems to be not related to libmediainfo. I replaced it with the system one and it made no difference. Then reverted it.
Replacing libzen with the system one did the trick.

**Comment by and1g** [comment]
With libzen.so from /usr/lib:

    2016-01-02 14:08:26,632 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (20%) loading MediaInfo libs
    2016-01-02 14:08:26,655 DEBUG [main] o.t.thirdparty.MediaInfoUtils:87 - Loading native mediainfo lib from: native/linux-x64
    Looking in classpath from sun.misc.Launcher$AppClassLoader@4e25154f for /com/sun/jna/linux-x86-64/libjnidispatch.so
    Found library resource at jar:file:/home/andreas/tmm/lib/jna.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
    Looking for library 'file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0'
    Adding paths from jna.library.path: native/linux-x64
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0.so
    Looking for version variants
    Looking in classpath from sun.misc.Launcher$AppClassLoader@4e25154f for file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0
    Looking for library 'zen'
    Adding paths from jna.library.path: native/linux-x64
    Trying /home/andreas/tmm/native/linux-x64/libzen.so
    Found library 'zen' at /home/andreas/tmm/native/linux-x64/libzen.so
    Looking for library 'file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0'
    Adding paths from jna.library.path: native/linux-x64
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0.so
    Looking for version variants
    Looking in classpath from sun.misc.Launcher$AppClassLoader@4e25154f for file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0
    Looking for library 'mediainfo'
    Adding paths from jna.library.path: native/linux-x64
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Looking for version variants
    Trying /usr/lib64/libmediainfo.so.0
    Found library 'mediainfo' at /usr/lib64/libmediainfo.so.0
    Looking for library 'mediainfo'
    Adding paths from jna.library.path: native/linux-x64
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Looking for version variants
    Trying /usr/lib64/libmediainfo.so.0
    Found library 'mediainfo' at /usr/lib64/libmediainfo.so.0
    2016-01-02 14:08:26,782 INFO  [main] o.t.thirdparty.MediaInfoUtils:92 - Using MediaInfoLib - v0.7.80
    2016-01-02 14:08:26,783 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (30%) loading movie module
    2016-01-02 14:08:27,053 INFO  [main] o.tinymediamanager.core.movie.MovieList:318 - found 0 movies in database
    2016-01-02 14:08:27,053 INFO  [main] o.tinymediamanager.core.movie.MovieList:338 - found 0 movieSets in database
    2016-01-02 14:08:27,054 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (40%) loading TV show module
    2016-01-02 14:08:27,093 INFO  [main] o.t.core.tvshow.TvShowList:255 - found 0 TV shows in database
    2016-01-02 14:08:27,093 INFO  [main] o.t.core.tvshow.TvShowList:285 - found 0 episodes in database
    2016-01-02 14:08:27,094 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (50%) loading plugins
    2016-01-02 14:08:27,120 DEBUG [main] org.tinymediamanager.core.PluginManager:64 - loading classpath plugins...
    2016-01-02 14:08:27,121 DEBUG [main] org.tinymediamanager.core.PluginManager:72 - Done loading classpath plugins - took 00:00:00.000
    2016-01-02 14:08:27,121 DEBUG [main] org.tinymediamanager.core.PluginManager:77 - loading external plugins...
    2016-01-02 14:08:27,193 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:240 - searching for Kodi commons
    2016-01-02 14:08:27,260 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.musicbrainz.org - ID already imported, or version lower
    2016-01-02 14:08:27,262 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.htbackdrops.com - ID already imported, or version lower
    2016-01-02 14:08:27,263 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.allmusic.com - ID already imported, or version lower
    2016-01-02 14:08:27,265 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.fanart.tv - ID already imported, or version lower
    2016-01-02 14:08:27,268 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.imdb.com - ID already imported, or version lower
    2016-01-02 14:08:27,270 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.themoviedb.org - ID already imported, or version lower
    2016-01-02 14:08:27,272 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.common.theaudiodb.com - ID already imported, or version lower
    2016-01-02 14:08:27,272 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.musicbrainz.org/musicbrainz.xml
    2016-01-02 14:08:27,272 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.htbackdrops.com/htbackdrops.xml
    2016-01-02 14:08:27,272 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.allmusic.com/allmusic.xml
    2016-01-02 14:08:27,273 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.fanart.tv/fanarttv.xml
    2016-01-02 14:08:27,273 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.imdb.com/imdb.xml
    2016-01-02 14:08:27,273 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.themoviedb.org/tmdb.xml
    2016-01-02 14:08:27,273 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /home/andreas/.kodi/addons/metadata.common.theaudiodb.com/tadb.xml
    2016-01-02 14:08:27,273 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:319 - Found common: /usr/share/kodi/addons/metadata.common.last.fm/lastfm.xml
    2016-01-02 14:08:27,273 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:170 - searching for Kodi scrapers
    2016-01-02 14:08:27,303 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.musicvideos.theaudiodb.com - ID already imported, or version lower
    2016-01-02 14:08:27,307 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.album.universal - ID already imported, or version lower
    2016-01-02 14:08:27,310 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.themoviedb.org - ID already imported, or version lower
    2016-01-02 14:08:27,314 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.artists.universal - ID already imported, or version lower
    2016-01-02 14:08:27,317 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:153 - not adding /usr/share/kodi/addons/metadata.tvdb.com - ID already imported, or version lower
    2016-01-02 14:08:27,317 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: /home/andreas/.kodi/addons/metadata.musicvideos.theaudiodb.com/tadb.xml
    2016-01-02 14:08:27,317 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: /home/andreas/.kodi/addons/metadata.album.universal/albumuniversal.xml
    2016-01-02 14:08:27,318 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: /home/andreas/.kodi/addons/metadata.themoviedb.org/tmdb.xml
    2016-01-02 14:08:27,318 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: /home/andreas/.kodi/addons/metadata.artists.universal/artistuniversal.xml
    2016-01-02 14:08:27,318 DEBUG [main] o.tinymediamanager.scraper.kodi.KodiUtil:204 - Found scraper: /home/andreas/.kodi/addons/metadata.tvdb.com/tvdb.xml
    2016-01-02 14:08:27,420 DEBUG [main] org.tinymediamanager.core.PluginManager:85 - Done loading external plugins - took 00:00:00.298
    2016-01-02 14:08:27,421 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (80%) loading ui
    2016-01-02 14:08:27,549 DEBUG [main] o.tinymediamanager.ui.movies.MoviePanel:180 - loading MovieList
    2016-01-02 14:08:28,120 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (100%) finished starting :)
    2016-01-02 14:08:28,129 DEBUG [trackEventThread] org.tinymediamanager.scraper.http.Url:232 - getting http://www.google-analytics.com/collect?v=1&tid=UA-35564534-5&cid=47ee9720-4c87-44b7-829e-40ebfd220af6&an=tinyMediaManager&av=2.7.1&t=event&ec=startup&ea=startup&aip=1&je=1&sc=start&ul=de-DE&vp=1100x727&cd1=Linux&cd2=amd64&cd3=1.8&cd4=2.7.1&cd5=0&z=1451740108122&sr=2880x1620
    2016-01-02 14:08:28,193 ERROR [trackEventThread] org.tinymediamanager.scraper.http.Url:263 - Exception getting url http://www.google-analytics.com/collect?v=1&tid=UA-35564534-5&cid=47ee9720-4c87-44b7-829e-40ebfd220af6&an=tinyMediaManager&av=2.7.1&t=event&ec=startup&ea=startup&aip=1&je=1&sc=start&ul=de-DE&vp=1100x727&cd1=Linux&cd2=amd64&cd3=1.8&cd4=2.7.1&cd5=0&z=1451740108122&sr=2880x1620
    java.net.ConnectException: Verbindungsaufbau abgelehnt
            at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_66]
            at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_66]
            at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204) ~[na:1.8.0_66]
            at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_66]
            at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66]
            at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66]
            at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100) ~[okhttp.jar:na]
            at com.squareup.okhttp.Connection.connectSocket(Connection.java:196) ~[okhttp.jar:na]
            at com.squareup.okhttp.Connection.connect(Connection.java:172) ~[okhttp.jar:na]
            at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367) ~[okhttp.jar:na]
            at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) ~[okhttp.jar:na]
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328) ~[okhttp.jar:na]
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) ~[okhttp.jar:na]
            at com.squareup.okhttp.Call.getResponse(Call.java:267) ~[okhttp.jar:na]
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224) ~[okhttp.jar:na]
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195) ~[okhttp.jar:na]
            at com.squareup.okhttp.Call.execute(Call.java:79) ~[okhttp.jar:na]
            at org.tinymediamanager.scraper.http.Url.getInputStream(Url.java:246) ~[api-scraper.jar:1.1]
            at org.tinymediamanager.core.Utils$2.run(Utils.java:522) [tmm.jar:2.7.1]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
    2016-01-02 14:08:33,121 INFO  [updateThread] org.tinymediamanager.core.UpdaterTask:67 - Checking for updates...
    2016-01-02 14:08:33,122 DEBUG [updateThread] org.tinymediamanager.scraper.http.Url:232 - getting http://release.tinymediamanager.org/build/digest.txt?z=1451740113122
    2016-01-02 14:08:33,267 INFO  [updateThread] org.tinymediamanager.core.UpdaterTask:150 - Already up2date :)
    2016-01-02 14:08:33,300 DEBUG [main] org.tinymediamanager.ui.MainWindow:300 - update result was: false

With the original libzen.so:

    2016-01-02 14:10:20,226 DEBUG [main] org.tinymediamanager.TinyMediaManager:397 - Startup (20%) loading MediaInfo libs
    2016-01-02 14:10:20,250 DEBUG [main] o.t.thirdparty.MediaInfoUtils:87 - Loading native mediainfo lib from: native/linux-x64
    Looking in classpath from sun.misc.Launcher$AppClassLoader@4e25154f for /com/sun/jna/linux-x86-64/libjnidispatch.so
    Found library resource at jar:file:/home/andreas/tmm/lib/jna.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
    Looking for library 'file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0'
    Adding paths from jna.library.path: native/linux-x64
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0.so
    Looking for version variants
    Looking in classpath from sun.misc.Launcher$AppClassLoader@4e25154f for file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libzen.so.0
    Looking for library 'zen'
    Adding paths from jna.library.path: native/linux-x64
    Trying /home/andreas/tmm/native/linux-x64/libzen.so
    Found library 'zen' at /home/andreas/tmm/native/linux-x64/libzen.so
    Looking for library 'file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0'
    Adding paths from jna.library.path: native/linux-x64
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying libfile:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0.so
    Looking for version variants
    Looking in classpath from sun.misc.Launcher$AppClassLoader@4e25154f for file:/home/andreas/tmm/tmm.jar!/org/tinymediamanager/thirdparty/libmediainfo.so.0
    Looking for library 'mediainfo'
    Adding paths from jna.library.path: native/linux-x64
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Looking for version variants
    Trying /usr/lib64/libmediainfo.so.0
    Found library 'mediainfo' at /usr/lib64/libmediainfo.so.0
    Looking for library 'mediainfo'
    Adding paths from jna.library.path: native/linux-x64
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Adding system paths: [/usr/lib64, /lib64, /usr/lib, /lib, /usr/lib32, /lib32, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3, /usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/32, /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/32, /usr/lib64/sidplay/builders, /usr/lib64/opencollada, /usr/lib64/R/lib, /usr/lib64/qt4, /usr/lib32/qt4]
    Trying /home/andreas/tmm/native/linux-x64/libmediainfo.so
    Looking for version variants
    Trying /usr/lib64/libmediainfo.so.0
    Found library 'mediainfo' at /usr/lib64/libmediainfo.so.0
    [1]    24229 segmentation fault (core dumped)  java -classpath  -Dcom.threerings.getdown=true -Xms64m -Xmx512m -Xss512k

**Comment by mlaggner** [comment]
okay, should work with the latest nightly builds/devel branch (shipping of mediainfo for Linux is now cancelled)
